#!/usr/bin/env zsh

echo "Setting up ssh keys"
ssh_dir=~/.ssh
# ensure directory exists
if [ ! -d $ssh_dir ]; then
  echo "---> creating $ssh_dir"
  mkdir $ssh_dir
fi
# with the correct permissions
if [ "$(ls -ld $ssh_dir | cut -f 1 -d ' ')" != "drwx------" ]; then
  echo "---> setting permissions on $ssh_dir"
  chmod 700 $ssh_dir
fi

ensure_key_exists() {
  keyfile=$ssh_dir/$1
  if [ ! -f $keyfile ]; then
    echo "---> creating $keyfile"
    ssh-keygen -f $keyfile -t ed25519 
  fi
}
ensure_key_exists id_ed25519
ensure_key_exists github_ed25519
echo "---> done"
