#!/usr/bin/env zsh

echo "Setting up dotfiles checkout"
dotfiles_url=https://github.com/rjernst/dotfiles.git
if [ "$USER"=="rjernst" ]; then
  dotfiles_url=git@github.com:rjernst/dotfiles.git
  echo "---> Checking authentication with github"
  ssh -T git@github.com &> /dev/null
  if [ $? -ne 1 ]; then
    echo "---> SSH authentication failed with github. Add the following ssh key to github:\n"
    cat ~/.ssh/id_ed25519.pub
    echo ""
    read -s -k "?Press any key when ready to continue"
  fi
fi

DOTFILES=~/.dotfiles
if [ ! -d $DOTFILES ]; then
  git clone $dotfiles_url $DOTFILES
fi
