#!/usr/bin/env zsh

# this is the "real" bootstrap, once dotfiles exist locally on the machine
script_path="${0:A:h}"

run_script() {
  source $script_path/$1
}

run_script bootstrap-ssh-keys
run_script bootstrap-dotfiles-checkout
run_script bootstrap-git
run_script ../setup
