#!/usr/bin/env bash

BASE_URL=https://raw.githubusercontent.com/rjernst/dotfiles/master/platform
curl -s $BASE_URL/detect | source /dev/stdin

case "$PLATFORM" in
  'macos')
    bash <(curl -s $BASE_URL/macos/bootstrap)
    ;;
  'arch')
    bash <(curl -s $BASE_URL/arch/bootstrap)
    ;;
  *)
    echo "Unsupported platform $PLATFORM"
    ;; 
esac
