#!/usr/bin/env zsh

local ZSHFILES=$HOME/.zsh


source $ZSHFILES/env.zsh
source $ZSHFILES/aliases.zsh

PLATFORM=$($DOTFILES/scripts/detect-platform)
for plugin in $ZSHFILES/plugins/*.zsh; do
  source $plugin
done
for file in $ZSHFILES/d/*.zsh; do
  source $file
done

INCLUDES=$DOTFILES/plugins
source $INCLUDES/zsh-completions/zsh-completions.plugin.zsh
source $INCLUDES/zsh-history-substring-search/zsh-history-substring-search.zsh
source $INCLUDES/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[ $SSH_AUTH_SOCK == /tmp/* ]]; then
  # Fix SSH auth socket location so agent forwarding works with tmux
  ln -sf $SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
  export SSH_AUTH_SOCK
else
  # connect ssh agent to gpg for key retrieval
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
  gpg-connect-agent updatestartuptty /bye >/dev/null
fi

HISTFILE=$HOME/.zsh/var/history
HISTSIZE=10000
SAVEHIST=10000

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _complete
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'

autoload -U compinit && compinit -d $HOME/.zsh/var/compdump
zmodload -i zsh/complist
zmodload -i zsh/zle

unsetopt menu_complete
unsetopt flowcontrol

setopt always_to_end
setopt append_history
setopt auto_menu
setopt complete_in_word
setopt extended_history
setopt extended_glob
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt interactivecomments
setopt share_history

bindkey -v

#source $ZSHFILES/prompt/99-prompt.zsh
for file in $(ls $ZSHFILES/prompt | sort -V); do
  source $ZSHFILES/prompt/$file
done

