#!/usr/bin/env zsh

export ZSHFILES=$HOME/.zsh
source $ZSHFILES/env
source $ZSHFILES/aliases
source $ZSHFILES/fzf
source $ZSHFILES/iterm2
#eval `dircolors $ZSHFILES/colors`

INCLUDES=$DOTFILES/plugins
source $INCLUDES/zsh-completions/zsh-completions.plugin.zsh
source $INCLUDES/zsh-history-substring-search/zsh-history-substring-search.zsh
source $INCLUDES/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Fix SSH auth socket location so agent forwarding works with tmux
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

HISTFILE=$HOME/.zsh/history
HISTSIZE=10000
SAVEHIST=10000

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _complete
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'

autoload -U compinit && compinit -d $HOME/.zsh/compdump
zmodload -i zsh/complist
zmodload -i zsh/zle

unsetopt menu_complete
unsetopt flowcontrol

setopt always_to_end
setopt append_history
setopt auto_menu
setopt complete_in_word
setopt extended_history
setopt extended_glob
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt interactivecomments
setopt share_history

bindkey -v

source $ZSHFILES/prompt
