#!/usr/bin/env bash

brew install nativefier

cd /tmp

nativefier -n "$1 Inbox" --fast-quit --disable-context-menu --single-instance --darwin-dark-mode-support --icon $DOTFILES/resources/$1\ inbox.icns https://mail.google.com

mv "/tmp/$1 Inbox-darwin-x64/$1 Inbox.app" /Applications

brew rmtree nativefier
