#!/usr/bin/env bash
# pinentry curses won't seem to work on macos, so this shell script
# wraps calling the correct one
case $PINENTRY_USER_DATA in
mac)
  exec pinentry-mac "$@"
  ;;
curses|*)
  exec pinentry-curses "$@"
  ;;
esac
