#!/usr/bin/env bash

DOTFILES=/tmp/dotfiles
ANSIBLE_PLAYBOOK=$DOTFILES/ansible
ANSIBLE_CONFIG=/tmp/ansible.cfg
clone_dotfiles() {
  if [ -d "$DOTFILES" ]; then
    rm -rf $DOTFILES
  fi
  echo "---> cloning ansible scripts"
  git clone https://github.com/rjernst/dotfiles.git $DOTFILES
}

bootstrap_macos() {
  command -v brew &> /dev/null || {
    echo "---> installing homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  }
  command -v ansible &> /dev/null || {
    echo "---> installing ansible"
    brew install ansible
  }
  command -v git &> /dev/null || {
    echo "---> installing git"
    brew install git
  }
}

bootstrap_arch() {
  echo "---> set root password"
  passwd
  echo "---> installing ansible"
  pacman -S --noconfirm --needed ansible
  echo "---> installing git"
  pacman -S --noconfirm --needed git
  
  clone_dotfiles

  echo "---> setting local ansible hosts file"
  echo -e "[localhost]\n127.0.0.1\tansible_connection=local" > /etc/ansible/hosts
  echo "---> creating temporary ansible config"
  echo -e "[defaults]\nroles_path=$ANSIBLE_PLAYBOOK/roles" > $ANSIBLE_CONFIG
  echo "---> running bootstrap playbook" 
  ansible-playbook -vv $ANSIBLE_PLAYBOOK/plays/arch-bootstrap.yml "$@"
}

BASE_URL=https://raw.githubusercontent.com/rjernst/dotfiles/master
PLATFORM=$(curl -s $BASE_URL/scripts/detect-platform | bash)
echo "---> detected platform: $PLATFORM"

case "$PLATFORM" in
  'macos')
    bootstrap_macos        
    ;;
  'arch')
    bootstrap_arch
    ;;
  *)
    echo "unsupported platform $PLATFORM"
    ;; 
esac
