
ZDOTDIR=$HOME/.zsh
DOTFILES=$HOME/.dotfiles
export EDITOR=/usr/bin/vim

if [[ $OSTYPE == darwin* ]]; then
  export PATH=/opt/homebrew/bin:$PATH
fi
export PATH=~/bin:$PATH

#----------------------------------------------------------------------------
#                                 zinit
#----------------------------------------------------------------------------
### Added by Zinit's installer
if [[ ! -f $ZDOTDIR/zinit/bin/zinit.zsh ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
  command mkdir -p "$ZDOTDIR/zinit" && command chmod g-rwX "$ZDOTDIR/zinit"
  command git clone https://github.com/zdharma-continuum/zinit "$ZDOTDIR/zinit/bin" && \
      print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
      print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

declare -A ZINIT
ZINIT[HOME_DIR]=$ZDOTDIR/zinit
ZINIT[ZCOMPDUMP_PATH]=$ZDOTDIR/var/zcompdump

source "$ZDOTDIR/zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk


#----------------------------------------------------------------------------
#                                 colors
#----------------------------------------------------------------------------
# turn on colors in both output, and completions
export CLICOLOR=1
zinit ice wait lucid atclone"dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"'
zinit light trapd00r/LS_COLORS

#----------------------------------------------------------------------------
#                                 completions
#----------------------------------------------------------------------------

zinit wait lucid for \
  atinit"zicompinit -; zicdreplay; zcompile -U \$ZDOTDIR/var/zcompdump" \
      zdharma-continuum/fast-syntax-highlighting \
      OMZP::colored-man-pages \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions

#----------------------------------------------------------------------------
#                                   history 
#----------------------------------------------------------------------------

# don't let history files pollute homedir
# disable less history so it doesn't write .lesshst
export LESSHISTSIZE=0
HISTFILE=$HOME/.zsh/var/history

# save a lot of history!
HISTSIZE=10000
SAVEHIST=10000
setopt hist_expire_dups_first
setopt hist_ignore_space

# append history immediately, but don't share across terminals
setopt inc_append_history

# don't pollute history
setopt hist_ignore_dups

# allow editing of line after selecting history
setopt hist_verify

# shortcuts
alias h='history'
alias hs='history | grep -i'

#----------------------------------------------------------------------------
#                               input line
#----------------------------------------------------------------------------

# allow comments so scripts can be pasted as is
setopt interactivecomments

# cursor movement
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

#----------------------------------------------------------------------------
#                                    git
#----------------------------------------------------------------------------
zinit wait lucid for \
      OMZL::git.zsh \
  atload"unalias grv" \
      OMZP::git

#zinit ice wait'1' atload'zinc_optional_depenency_loaded'
#zinit load romkatv/gitstatus

#----------------------------------------------------------------------------
#                                  gradle 
#----------------------------------------------------------------------------
# where gradle looks for gradle.properties
export GRADLE_USER_HOME=$HOME/.gradle
# helper for running gradlew from any dir
alias gw='$DOTFILES/scripts/gradlew.sh'

#----------------------------------------------------------------------------
#                                  python
#----------------------------------------------------------------------------
alias py3='python3'

for plugin in $ZDOTDIR/plugins/*.zsh(N); do
  source $plugin
done

#----------------------------------------------------------------------------
#                               basic shortcuts
#----------------------------------------------------------------------------
alias cdd='cd $DOTFILES'
[[ $OSTYPE == linux* ]] && alias ls='ls --group-directories-first'
alias ll='ls -l'
alias rm='rm -i'       # always ask before removing a file
alias mv='mv -i'       # always ask before moving a file onto another file
alias cp='cp -i'       # always ask before copying a file onto another file
alias grep='grep --color=auto'
alias d='docker'

#----------------------------------------------------------------------------
#                             dotfiles management
#----------------------------------------------------------------------------
alias reload-config='echo "Reloading $HOME/.zshrc"; source $HOME/.zshrc'
if [[ $OSTYPE == darwin* ]]; then

  function _reload_brewfile() {
    echo "Updating homebrew bundles from $HOME/.Brewfile"
    brew bundle --global install 

    x86brewfile=~/.Brewfile-x86
    if [[ -f $x86brewfile && -f /usr/local/bin/brew ]]; then
      arch -x86_64 /bin/bash -c "/usr/local/bin/brew bundle --file $x86brewfile install"
    fi
  }
  alias reload-brewfile='_reload_brewfile'
  alias edit-brewfile='vim $HOME/.Brewfile'
  alias edit-brewfile-x86='vim $HOME/.Brewfile-x86'

  function _brew_x86() {
    arch -x86_64 /bin/bash -c "/usr/local/bin/brew $@"
  }
  alias brew-x86='_brew_x86'
fi
function _reload_ssh_keys() {
  if [[ $(uname) == "Darwin" ]]; then
    SSH_ADD_OPTIONS="--apple-use-keychain"
  fi
  keys=('id_ed25519' 'github_ed25519')
  for key in $keys; do
    ssh-add $SSH_ADD_OPTIONS ~/.ssh/$key
  done
}
alias reload-ssh-keys='_reload_ssh_keys'
function _refresh_dotfiles() {
  echo "Pulling latest dotfiles..."
  if ! git -C "$DOTFILES" pull --ff-only; then
    echo "Pull failed. Your local branch may have diverged."
    echo "  cd $DOTFILES && git status"
    return 1
  fi

  echo "Running setup..."
  if ! "$DOTFILES/setup"; then
    echo ""
    echo "Setup had errors (see above). Your shell should still work."
    echo "Fix the issue and run 'refresh-dotfiles' again."
    return 1
  fi

  # Clear any stale update notification
  rm -f "$ZDOTDIR/var/dotfiles-behind-count"

  reload-config
}
alias refresh-dotfiles=_refresh_dotfiles

#----------------------------------------------------------------------------
#                               starship prompt
#----------------------------------------------------------------------------
eval "$(starship init zsh)"

# Transient prompt: collapse previous prompts to just ❯
__starship_saved_prompt="$PROMPT"
__starship_saved_rprompt="$RPROMPT"
zle-line-finish() {
  PROMPT='%(?.%F{green}.%F{red})❯%f '
  RPROMPT=''
  zle reset-prompt
  PROMPT="$__starship_saved_prompt"
  RPROMPT="$__starship_saved_rprompt"
}
zle -N zle-line-finish

# vi: set tabstop=2 shiftwidth=2 filetype=sh expandtab:

if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi
